{% set version = "0.94.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quanteda.textplots
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quanteda.textplots_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quanteda.textplots/quanteda.textplots_{{ version }}.tar.gz
  sha256: 6649cfba86ed34cd81a9951bb392700697e095f5986381ed9d2fa87959a85bb9

build:
  merge_build_host: true  # [win]
  number: 1
  # rttf2pt1 dependency not available on windows
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcolorbrewer
    - r-rcpp >=0.12.12
    - r-extrafont
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-network
    - r-quanteda
    - r-sna
    - r-stringi
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcolorbrewer
    - r-rcpp >=0.12.12
    - r-extrafont
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-network
    - r-quanteda
    - r-sna
    - r-stringi

test:
  commands:
    - $R -e "library('quanteda.textplots')"           # [not win]
    - "\"%R%\" -e \"library('quanteda.textplots')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=quanteda.textplots
  license: GPL-3.0-only
  summary: Plotting functions for visualising textual data.  Extends 'quanteda' and related packages with plot methods designed specifically for text data, textual statistics, and models fit to textual data. Plot types include word clouds, lexical dispersion plots, scaling plots, network visualisations, and word 'keyness'
    plots.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
